"""P2-04 上游升级与无补丁治理门测试。

验证治理门本身有检测能力：用临时假仓库构造违规 fixture（VCS/editable/path/未锁定
依赖来源、任意位置影子包、vendor/fork 目录变体、上游源码副本、生产 Monkey-patch），
守卫必须失败；合法 tests 中的 mock patch、venv/node_modules/缓存中的真实安装不误报。
"""

from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
GATE = REPO_ROOT / "scripts" / "upgrade_governance_gate.py"

LOCK_HEADER = (
    "# This file is autogenerated by pip-compile with Python 3.12\n"
    "# by the following command:\n"
    "#\n"
    "#    pip-compile --resolver=backtracking --strip-extras --extra=dev "
    "--output-file=requirements.lock pyproject.toml\n"
)

CLEAN_PYPROJECT = (
    "[project]\n"
    'name = "fixture"\n'
    'version = "0.0.0"\n'
    'dependencies = ["flask==3.1.3", "pdf2zh-next==2.9.0"]\n'
    "[project.optional-dependencies]\n"
    'dev = ["pytest==9.0.3"]\n'
)

CLEAN_LOCK = (
    LOCK_HEADER
    + "\n"
    + "flask==3.1.3\n    # via fixture\n"
    + "pdf2zh-next==2.9.0\n    # via fixture\n"
    + "babeldoc==0.6.2\n    # via pdf2zh-next\n"
)


def _load_gate() -> ModuleType:
    spec = importlib.util.spec_from_file_location("upgrade_governance_gate", GATE)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _write(root: Path, rel: str, text: str = "") -> Path:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def _fake_repo(tmp_path: Path, files: dict[str, str]) -> Path:
    root = tmp_path / "fake-repo"
    root.mkdir(parents=True, exist_ok=True)
    _write(root, "pyproject.toml", CLEAN_PYPROJECT)
    _write(root, "requirements.lock", CLEAN_LOCK)
    for rel, text in files.items():
        _write(root, rel, text)
    return root


def _copy_marker() -> str:
    return "class " + "Automatic" + "TermExtractor" + ":\n    pass\n"


def _shared_context_marker() -> str:
    return "class " + "SharedContext" + "CrossSplitPart" + ":\n    pass\n"


def _run_static(root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(GATE), "--repo-root", str(root), "--static-only"],
        capture_output=True,
        text=True,
        timeout=120,
    )


def test_clean_fixture_passes_static_checks(tmp_path):
    gate = _load_gate()
    root = _fake_repo(tmp_path, {})
    assert gate.check_all_static(root) == []


@pytest.mark.parametrize(
    "dependency",
    [
        "pdf2zh-next @ git+https://github.com/user/pdf2zh-next.git@main",
        "flask @ git+https://github.com/user/flask.git@v3.1.3",
        "git+https://github.com/user/babeldoc.git",
        "flask @ https://files.pythonhosted.org/packages/flask-3.1.3-py3-none-any.whl",
        "flask @ file:///tmp/flask-3.1.3-py3-none-any.whl",
        "-e ./local-package",
        "./local-package",
    ],
)
def test_rejects_vcs_editable_path_and_direct_reference_sources(tmp_path, dependency):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "pyproject.toml": CLEAN_PYPROJECT.replace(
                '"pdf2zh-next==2.9.0"',
                '"pdf2zh-next==2.9.0", ' + repr(dependency),
            )
        },
    )
    violations = gate.check_dependency_sources(root)
    assert violations, f"dependency fixture must be rejected: {dependency!r}"
    assert any("pyproject.toml" in v for v in violations)


def test_rejects_unpinned_runtime_dependency(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "pyproject.toml": CLEAN_PYPROJECT.replace(
                '"pdf2zh-next==2.9.0"',
                '"pdf2zh-next>=2.9"',
            )
        },
    )
    violations = gate.check_dependency_sources(root)
    assert any("exact-pinned" in v for v in violations)


def test_rejects_vcs_and_unpinned_lock_lines(tmp_path):
    gate = _load_gate()
    bad_locks = (
        CLEAN_LOCK + "pdf2zh-next @ git+https://github.com/user/pdf2zh-next.git@main\n",
        CLEAN_LOCK + "flask\n",
        CLEAN_LOCK + "-e .\n",
    )
    for bad in bad_locks:
        root = _fake_repo(tmp_path, {"requirements.lock": bad})
        violations = gate.check_dependency_sources(root)
        assert violations, f"lock fixture must be rejected: {bad[-60:]!r}"


@pytest.mark.parametrize(
    "dependency",
    [
        "evil==git+https://example/fork.git@main",
        "evil==git://example/repo.git",
        "evil==file:///tmp/pkg.whl",
        "evil==https://example/pkg.whl",
    ],
)
def test_rejects_disguised_source_after_exact_pin_in_pyproject(tmp_path, dependency):
    """依赖来源 fail-closed：VCS/direct URL/file URL 伪装在 == 之后也必须拒绝。"""
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "pyproject.toml": CLEAN_PYPROJECT.replace(
                '"pdf2zh-next==2.9.0"',
                '"pdf2zh-next==2.9.0", ' + repr(dependency),
            )
        },
    )
    violations = gate.check_dependency_sources(root)
    assert violations, f"disguised dependency fixture must be rejected: {dependency!r}"
    assert any("pyproject.toml" in v for v in violations)


@pytest.mark.parametrize(
    "line",
    [
        "evil==git+https://example/fork.git@main",
        "evil==git://example/repo.git",
        "evil==file:///tmp/pkg.whl",
        "evil==https://example/pkg.whl",
    ],
)
def test_rejects_disguised_source_after_exact_pin_in_lock(tmp_path, line):
    gate = _load_gate()
    root = _fake_repo(tmp_path, {"requirements.lock": CLEAN_LOCK + line + "\n"})
    violations = gate.check_dependency_sources(root)
    assert violations, f"disguised lock fixture must be rejected: {line!r}"
    assert any("requirements.lock" in v for v in violations)


def test_accepts_legal_pep440_exact_versions_without_false_positive(tmp_path):
    """合法的 PEP 440 精确版本（含 post/local 段）不得被来源检查误伤。"""
    gate = _load_gate()
    pyproject = (
        "[project]\n"
        'name = "fixture"\n'
        'version = "0.0.0"\n'
        "dependencies = [\n"
        '  "flask==3.1.3",\n'
        '  "pdf2zh-next==2.9.0",\n'
        '  "pkg-a==2024.1.1.post1",\n'
        '  "pkg_b==1.0+local",\n'
        "]\n"
        "[project.optional-dependencies]\n"
        'dev = ["pytest==9.0.3"]\n'
    )
    lock = CLEAN_LOCK + ("pkg-a==2024.1.1.post1\n    # via fixture\npkg_b==1.0+local\n    # via fixture\n")
    root = _fake_repo(tmp_path, {"pyproject.toml": pyproject, "requirements.lock": lock})
    assert gate.check_dependency_sources(root) == []


def test_rejects_upstream_pin_drift_between_pyproject_and_lock(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "pyproject.toml": CLEAN_PYPROJECT.replace(
                '"pdf2zh-next==2.9.0"',
                '"pdf2zh-next==2.9.1"',
            )
        },
    )
    violations = gate.check_dependency_sources(root)
    assert any("pdf2zh-next" in v and "2.9.1" in v for v in violations)


def test_rejects_babeldoc_declared_in_pyproject_as_direct_dependency(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "pyproject.toml": CLEAN_PYPROJECT.replace(
                '"pdf2zh-next==2.9.0"',
                '"pdf2zh-next==2.9.0", "babeldoc==0.6.2"',
            )
        },
    )
    violations = gate.check_dependency_sources(root)
    assert any("babeldoc" in v and "transitive" in v for v in violations)


def test_detects_shadow_package_dirs_at_any_location(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "pdf2zh_next/__init__.py": "",
            "src/shims/babeldoc/__init__.py": "",
            "scripts/tools/pdf2zh_next/core.py": "",
        },
    )
    violations = gate.check_repo_governance(root)
    assert any("shadow package directory" in v and "pdf2zh_next" in v for v in violations)
    assert any("shadow package directory" in v and "babeldoc" in v for v in violations)


def test_detects_shadow_module_files(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "src/babeldoc.py": "x = 1\n",
            "tools/pdf2zh_next.py": "y = 2\n",
        },
    )
    violations = gate.check_repo_governance(root)
    assert any("shadow module file" in v and "babeldoc.py" in v for v in violations)
    assert any("shadow module file" in v and "pdf2zh_next.py" in v for v in violations)


def test_detects_fork_and_vendor_directory_variants(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "forks/PDFMathTranslate-next/src/pdf2zh_next/__init__.py": "",
            "third_party/babeldoc/upstream_copy.py": _copy_marker(),
            "vendor/extra.py": _shared_context_marker(),
        },
    )
    violations = gate.check_repo_governance(root)
    assert any("fork-like upstream directory" in v for v in violations)
    assert any("vendored upstream source directory" in v for v in violations)
    assert any("upstream source copy" in v and "third_party" in v for v in violations)


def test_detects_upstream_source_copy_at_arbitrary_location(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "docs/notes/upstream_copy.py": _shared_context_marker() + _copy_marker(),
            "tests/fixtures/also_a_copy.py": _copy_marker(),
        },
    )
    violations = gate.check_repo_governance(root)
    assert any("upstream source copy" in v and "docs/notes" in v for v in violations)
    assert any("upstream source copy" in v and "tests/fixtures" in v for v in violations)


def test_detects_production_monkey_patch_but_not_legit_test_patch(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "src/pdf_reader/app.py": ("pdf2zh_next.high_level.create_babeldoc_config = fake\n"),
            "tests/test_legit.py": (
                "from unittest.mock import patch\n"
                "\n"
                "def test_x():\n"
                "    with patch(\n"
                "        'babeldoc.format.pdf.translation_config."
                "SharedContextCrossSplitPart.get_glossaries_for_translation',\n"
                "        return_value=[],\n"
                "    ):\n"
                "        pass\n"
            ),
        },
    )
    violations = gate.check_monkey_patch(root)
    assert any("src/pdf_reader/app.py" in v for v in violations)
    assert not any("tests/test_legit.py" in v for v in violations)


def test_detects_nested_production_module_monkey_patch(tmp_path):
    """递归扫描 src/pdf_reader 下的嵌套生产包，tests 合法 patch 仍不误报。"""
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "src/pdf_reader/nested_pkg/engine.py": (
                "babeldoc.format.pdf.translation_config.TranslationConfig = fake\n"
            ),
            "tests/test_legit.py": (
                "from unittest.mock import patch\n"
                "\n"
                "def test_x():\n"
                "    with patch(\n"
                "        'babeldoc.format.pdf.translation_config."
                "SharedContextCrossSplitPart.get_glossaries_for_translation',\n"
                "        return_value=[],\n"
                "    ):\n"
                "        pass\n"
            ),
        },
    )
    violations = gate.check_monkey_patch(root)
    assert any("src/pdf_reader/nested_pkg/engine.py" in v for v in violations)
    assert not any("tests/test_legit.py" in v for v in violations)


def test_production_mock_import_is_rejected(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {"src/pdf_reader/config.py": "from unittest.mock import patch\n"},
    )
    violations = gate.check_monkey_patch(root)
    assert any("src/pdf_reader/config.py" in v for v in violations)


def test_excludes_venv_node_modules_caches_and_build(tmp_path):
    gate = _load_gate()
    root = _fake_repo(
        tmp_path,
        {
            "venv/Lib/site-packages/pdf2zh_next/__init__.py": "",
            "venv/Lib/site-packages/babeldoc/__init__.py": "",
            "node_modules/babeldoc/__init__.py": "",
            ".pytest_cache/pdf2zh_next/__init__.py": "",
            "build/pdf2zh_next/__init__.py": "",
            "cache/pdf2zh_next/__init__.py": "",
        },
    )
    assert gate.check_repo_governance(root) == []


def test_cli_static_only_detects_fixture_and_fails_nonzero(tmp_path):
    root = _fake_repo(tmp_path, {"vendor/pdf2zh_next/__init__.py": ""})
    result = _run_static(root)
    assert result.returncode == 1
    assert "UPGRADE GOVERNANCE GATE FAILED" in result.stdout
    assert "shadow package directory" in result.stdout
    assert "PASSED" not in result.stdout


def test_cli_static_only_passes_on_real_repo():
    result = _run_static(REPO_ROOT)
    assert result.returncode == 0, result.stderr
    assert "Upgrade governance gate PASSED" in result.stdout


def test_contract_selection_covers_required_invariants():
    gate = _load_gate()
    assert gate.CONTRACT_TEST_FILES == [
        "tests/test_dependency_contract.py",
        "tests/test_upstream_contract.py",
        "tests/test_upstream_boundary_governance.py",
        "tests/test_strict_glossary.py",
        "tests/test_glossary_compliance_flow.py",
        "tests/test_terminology_compliance.py",
        "tests/test_glossary_compiler.py",
        "tests/release/test_portable_processes.py",
    ]
    for rel in gate.CONTRACT_TEST_FILES:
        assert (REPO_ROOT / rel).is_file(), f"gate contract test missing: {rel}"


def test_verify_script_invokes_static_gate_and_ci_runs_verify():
    verify = (REPO_ROOT / "scripts" / "verify.ps1").read_text(encoding="utf-8")
    assert "upgrade_governance_gate.py" in verify
    assert "--static-only" in verify
    assert "Upgrade governance gate" in verify
    ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "scripts/verify.ps1" in ci


def test_docs_record_gate_command_and_scope():
    dep_upgrade = (REPO_ROOT / "docs" / "governance" / "dependency-upgrade.md").read_text(encoding="utf-8")
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    architecture = (REPO_ROOT / "docs" / "architecture.md").read_text(encoding="utf-8")
    for text in (dep_upgrade, readme):
        assert "python scripts/upgrade_governance_gate.py" in text
    for text in (dep_upgrade, architecture):
        assert "upgrade_governance_gate.py" in text
    assert "--static-only" in dep_upgrade
    assert "P2-04" in architecture


def test_gate_script_does_not_self_match_markers():
    text = GATE.read_text(encoding="utf-8")
    for marker in (
        "class " + "AutomaticTermExtractor" + ":",
        "class " + "SharedContextCrossSplitPart" + ":",
    ):
        assert marker not in text


@pytest.mark.skipif(os.name != "nt", reason="verify.ps1 is Windows/PowerShell-only")
def test_verify_full_script_accepts_static_gate_invocation(tmp_path):
    """verify.ps1 的全量 fake 运行路径必须兼容新增的静态治理门步骤。"""
    fake = tmp_path / "fake-bin"

    def write_cmd(path: Path, body: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body.replace("\n", "\r\n"), encoding="ascii")

    write_cmd(
        fake / "python.cmd",
        "@echo off\n@echo %~f0\n@echo 3.12.0\nexit /b 0\n",
    )
    write_cmd(fake / "npm.cmd", "@echo off\necho fake npm %*\nexit /b 0\n")
    env = os.environ.copy()
    env["PATH"] = str(fake) + os.pathsep + env["PATH"]
    env.pop("PYTHONPATH", None)
    result = subprocess.run(
        [
            "powershell",
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(REPO_ROOT / "scripts" / "verify.ps1"),
            "-PythonExecutable",
            str(fake / "python.cmd"),
        ],
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert result.returncode == 0, result.stderr
    assert "Upgrade governance gate" in result.stdout
