"""Windows version resources for the two frozen executables.

The version comes from ``pyproject.toml`` at build time, so both EXEs carry the same
file/product version as the ZIP name, the runtime manifest and the application.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

OPINIONS = "本程序按原样提供，不附带任何担保。"


def quad_version(version: str) -> str:
    """Return a four-part Windows version tuple from a PEP 440 release version."""

    match = re.match(r"^(\d+)(?:\.(\d+))?(?:\.(\d+))?", version)
    if not match:
        raise ValueError(f"cannot derive a Windows version from {version!r}")
    parts = [int(group) if group else 0 for group in match.groups()]
    while len(parts) < 4:
        parts.append(0)
    return ".".join(str(part) for part in parts[:4])


def render_version_info(*, version: str, executable_name: str, company: str = "PDF Reader") -> str:
    """Render a PyInstaller ``VSVersionInfo`` document for one executable."""

    numeric = quad_version(version)
    internal_name = executable_name[:-4] if executable_name.lower().endswith(".exe") else executable_name
    internal_literal = json.dumps(internal_name)[1:-1]
    return f"""# UTF-8
# Generated by packaging/windows/buildtool/winver.py from pyproject.toml; do not edit.
VSVersionInfo(
    ffi=FixedFileInfo(
        filevers=({numeric.replace(".", ", ")}),
        prodvers=({numeric.replace(".", ", ")}),
        mask=0x3F,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0),
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    '040904B0',
                    [
                        StringStruct('CompanyName', '{company}'),
                        StringStruct('FileDescription', 'PDF Reader Windows 便携版'),
                        StringStruct('FileVersion', '{version}'),
                        StringStruct('InternalName', '{internal_literal}'),
                        StringStruct('LegalCopyright', 'AGPL-3.0-only'),
                        StringStruct('OriginalFilename', '{executable_name}'),
                        StringStruct('ProductName', 'PDF Reader'),
                        StringStruct('ProductVersion', '{version}'),
                    ],
                )
            ]
        ),
        VarFileInfo([VarStruct('Translation', [1033, 1200])]),
    ],
)
"""


def write_version_info(path: Path, **kwargs: str) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_version_info(**kwargs), encoding="utf-8")
    return destination
